runtime: python37

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F2

service: notifications


env_variables:
  POSTGRES_USER: "household-planner"
  POSTGRES_SERVER: "household-planner-333519:us-central1:postgres-instance"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "household-planner"
  PROD: "True"
