runtime: python37

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F2

service: photos

env_variables:
  IMAGE_BUCKET: "image-household-planner-333519"
  SERVICE_ACCOUNT_MAIL: "household-planner-333519@appspot.gserviceaccount.com"
